### ISSUE TITLE
Fails with perls < 5.10

### ISSUE THREAD

**Issue by andk** [reneeb/OTRS-OPM-Maker-Command-sopm#1]
As per subject. Best illustrated with the matrix: 

http://matrix.cpantesters.org/?dist=OTRS-OPM-Maker-Command-sopm%201.34

Sample fail report: 

http://www.cpantesters.org/cpan/report/662da036-3d11-11e6-83c2-891a5cc2a771

My guess is that the // operator is to blame. 

https://metacpan.org/source/RENEEB/OTRS-OPM-Maker-Command-sopm-1.34/lib/OTRS/OPM/Maker/Command/sopm.pm#L171

But I have not tried what happens when it is removed.

It would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes 

Best,

**Comment by reneeb** [comment]
Fixed as of version 1.35...
